plugins {
    alias(libs.plugins.androidApplication)
}

android {
    namespace 'com.abmn.englishhub'
    compileSdk 36

    defaultConfig {
        applicationId "com.abmn.englishhub"
        minSdk 24
        //noinspection EditedTargetSdkVersion
        targetSdk 36
        versionCode 11
        versionName "1.1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.navigation.ui
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.play.services.ads

    implementation libs.gson
    implementation libs.volley
    implementation libs.utility
    implementation libs.texttospeech
}