plugins {
    alias(libs.plugins.androidApplication)
}

android {
    namespace 'com.abmn.englishhub'
    compileSdk 34

    defaultConfig {
        applicationId "com.abmn.englishhub"
        minSdk 23
        targetSdk 34
        versionCode 7
        versionName "1.0.7"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.navigation.ui
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.gson
    implementation libs.volley
    implementation libs.utility
}