import java.util.Properties

plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.google.gms.google.services)
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("keystore.properties")
def hasKeystoreProperties = keystorePropertiesFile.exists()
if (hasKeystoreProperties) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.abmn.englishhub'
    compileSdk 36

    defaultConfig {
        applicationId "com.abmn.englishhub"
        minSdk 24
        //noinspection EditedTargetSdkVersion
        targetSdk 36
        versionCode 16
        versionName "1.1.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        if (hasKeystoreProperties) {
            release {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (hasKeystoreProperties) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.navigation.ui
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.play.services.ads

    implementation libs.gson
    implementation libs.volley
    implementation libs.recyclerview
    implementation libs.swiperefreshlayout
    implementation libs.utility
    implementation libs.ucrop
    implementation libs.glide

    implementation platform(libs.firebase.bom)
    implementation libs.firebase.messaging
}